[package]
name = "qdb"
version = "0.1.0"
authors = ["VaskillerDev vaskoooo9241@gmail.com"]
edition = "2018"
build   = "build.rs"

[dependencies]
yaml-rust = "0.4.3"
clap = {version = "2.33", features = ["yaml"]}